#!/usr/bin/env python3
"""
Turns tools/sdk-backend-selected.json (tools/select-sdk-backend-candidates.py's
output) into real ADAPTERS entries in VeraSdkBackend.ets.

Every selected candidate is one of two mechanical shapes -- call a namespace
function with 0-2 simple-typed arguments, return a primitive or void -- so
this writes hundreds of near-identical functions rather than reasoning about
each one individually. What it generates:

  - One `import <name> from '<path>'` per unique (module, file) pair, sorted,
    inserted after the existing hand-written imports. A module name that
    comes from more than one file (this SDK has exactly one such collision:
    `connection` is both @ohos.net.connection and @ohos.bluetooth.connection)
    is imported under an alias derived from its file path instead of the bare
    module name, for every file it maps to -- so there is never a case where
    which file "won" the plain name matters.
  - Small `paramString`/`paramInt`/`paramFloat`/`paramBoolean`/`paramBigInt`
    helpers, reading a value out of the params map by its real name with a
    type-appropriate fallback when the model didn't supply it.
  - One ADAPTERS map entry per candidate, appended below a fixed marker line
    inside the existing `const ADAPTERS = new Map<...>([ ... ])` literal. The
    file's own header comment, the two hand-written storage entries above the
    marker, and the runSdkAdapter function after the map are never touched --
    this script only ever rewrites the marker line onward up to the map's
    closing `])`, so re-running it after a fresh selection is safe.

Usage:
    python3 tools/generate-sdk-backend.py \
        --selected tools/sdk-backend-selected.json \
        --out entry/src/main/ets/vera/VeraSdkBackend.ets
"""

import argparse
import json
import re

MARKER = '  // generated by tools/generate-sdk-backend.py -- do not hand-edit below this line'

PARAM_HELPER = {
    'string': ('paramString', "''"),
    'int': ('paramInt', '0'),
    'long': ('paramInt', '0'),
    'number': ('paramFloat', '0'),
    'double': ('paramFloat', '0'),
    'boolean': ('paramBoolean', 'false'),
    'bigint': ('paramBigInt', 'BigInt(0)'),
}

HELPER_BLOCK = '''
function paramString(params: Map<string, string>, name: string, fallback: string): string {
  let v = params.get(name)
  return v !== undefined ? v : fallback
}

// A value that is not a number is an error the program can see, not a NaN that
// the platform quietly reads as 0: a generated program passed ["mode", "OFF"]
// to setTorchMode, got "ok", and the flashlight never lit. runSdkAdapter turns
// the throw into "error: ..." as the answer.
function paramInt(params: Map<string, string>, name: string, fallback: number): number {
  let v = params.get(name)
  if (v === undefined) { return fallback }
  let n = Number.parseInt(v, 10)
  if (Number.isNaN(n)) { throw new Error('parameter ' + name + ' must be an integer, got "' + v + '"') }
  return n
}

function paramFloat(params: Map<string, string>, name: string, fallback: number): number {
  let v = params.get(name)
  if (v === undefined) { return fallback }
  let n = Number.parseFloat(v)
  if (Number.isNaN(n)) { throw new Error('parameter ' + name + ' must be a number, got "' + v + '"') }
  return n
}

function paramBoolean(params: Map<string, string>, name: string, fallback: boolean): boolean {
  let v = params.get(name)
  return v !== undefined ? v === 'true' : fallback
}

function paramBigInt(params: Map<string, string>, name: string, fallback: bigint): bigint {
  let v = params.get(name)
  return v !== undefined ? BigInt(v) : fallback
}
'''.strip('\n')

HELPER_MARKER = '// -- generated helpers below (tools/generate-sdk-backend.py) --'


def import_path(file_name):
    assert file_name.endswith('.d.ts'), file_name
    return file_name[:-len('.d.ts')]


def alias_for(file_name):
    """bluetooth.connection.d.ts-style tail of the import path, camelCased --
    used only for a module name that more than one file exports."""
    path = import_path(file_name)
    tail = path[len('@ohos.'):] if path.startswith('@ohos.') else path.lstrip('@').replace('/', '.')
    parts = [p for p in re.split(r'[.\-]', tail) if p]
    if not parts:
        return 'mod'
    return parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])


def build_import_table(selected):
    """(module, file) -> local identifier used both in the import statement
    and at every call site referencing that module."""
    files_by_module = {}
    for e in selected:
        files_by_module.setdefault(e['module'], set()).add(e['file'])

    table = {}
    for module, files in files_by_module.items():
        if len(files) == 1:
            table[(module, next(iter(files)))] = module
        else:
            for f in files:
                table[(module, f)] = alias_for(f)
    return table


def arg_expr(name, ptype):
    helper, fallback = PARAM_HELPER[ptype]
    return f"{helper}(params, '{name}', {fallback})"


def gen_entry(e, import_table):
    local = import_table[(e['module'], e['file'])]
    arg_names = []
    decls = []
    for name, ptype, _optional in e['params']:
        # A parameter that happens to share its module's own import name
        # (e.g. `socket(socket: int)` from `@ohos.bluetooth.socket`) would
        # shadow the module inside the function body, turning `socket.fn()`
        # into a call on the number itself -- give the local variable a
        # different name in that one case while keeping the wire-format
        # param name (what paramX reads out of the map) unchanged.
        local_var = name + '_' if name == local else name
        decls.append(f"    let {local_var} = {arg_expr(name, ptype)}")
        arg_names.append(local_var)
    call = f"{local}.{e['name']}({', '.join(arg_names)})"
    if e['isPromise']:
        call = f"await {call}"

    body = list(decls)
    if e['returnType'] == 'void':
        body.append(f"    {call}")
        body.append("    return 'ok'")
    else:
        body.append(f"    let result = {call}")
        body.append("    return result.toString()")

    inner = '\n'.join(body)
    return (
        f"  ['{e['target']}', async (params: Map<string, string>): Promise<string> => {{\n"
        f"{inner}\n"
        f"  }}],"
    )


def find_line(lines, predicate, start=0):
    for i in range(start, len(lines)):
        if predicate(lines[i]):
            return i
    raise SystemExit(f'expected a matching line from index {start} onward, found none')


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--selected', default='tools/sdk-backend-selected.json')
    ap.add_argument('--out', default='entry/src/main/ets/vera/VeraSdkBackend.ets')
    args = ap.parse_args()

    selected = json.load(open(args.selected, encoding='utf-8'))
    selected.sort(key=lambda e: e['target'])

    lines = open(args.out, encoding='utf-8').read().split('\n')

    map_open_idx = find_line(lines, lambda l: 'new Map<string, SdkAdapter>([' in l)
    try:
        marker_idx = find_line(lines, lambda l: l == MARKER, map_open_idx + 1)
        hand_written = lines[map_open_idx + 1:marker_idx]
        close_idx = find_line(lines, lambda l: l.strip() == '])', marker_idx + 1)
    except SystemExit:
        close_idx = find_line(lines, lambda l: l.strip() == '])', map_open_idx + 1)
        hand_written = lines[map_open_idx + 1:close_idx]

    pre = lines[:map_open_idx + 1]
    post = lines[close_idx + 1:]

    # Imports: fully recomputed every run, not merely appended to -- otherwise
    # a selection that drops a target (e.g. one needing a permission this app
    # turned out not to actually hold) leaves an unused import for a module
    # nothing calls any more. An existing import line survives only if it's
    # referenced from hand-written code -- a map entry above the marker, or a
    # hand-written helper in the "safe zone" between the type alias and the
    # generated-helpers marker (e.g. cameraManagerOnce's own import, which no
    # map entry mentions directly). Named imports (`import { X } from ...`)
    # are recognised the same as default ones, since a hand-written exception
    # is exactly where those show up.
    helper_marker_idx_orig = find_line(pre, lambda l: l == HELPER_MARKER)
    last_import_idx_orig = find_line(pre, lambda l: l.startswith('import '))
    while (last_import_idx_orig + 1 < len(pre)
           and pre[last_import_idx_orig + 1].startswith('import ')):
        last_import_idx_orig += 1
    safe_zone_text = '\n'.join(pre[last_import_idx_orig + 1:helper_marker_idx_orig])
    reference_text = '\n'.join(hand_written) + '\n' + safe_zone_text

    import_line_re = re.compile(r"^import (?:(\w+)|\{\s*(\w+)\s*\}) from '([^']+)'$")
    first_import_idx = find_line(pre, lambda l: l.startswith('import '))
    last_import_idx = first_import_idx
    while last_import_idx + 1 < len(pre) and pre[last_import_idx + 1].startswith('import '):
        last_import_idx += 1

    preserved = []
    preserved_locals = set()
    for l in pre[first_import_idx:last_import_idx + 1]:
        m = import_line_re.match(l)
        if not m:
            continue
        local = m.group(1) or m.group(2)
        if re.search(r'\b' + re.escape(local) + r'\.', reference_text):
            preserved.append(l)
            preserved_locals.add(local)

    import_table = build_import_table(selected)
    generated_imports = sorted(
        {(local, import_path(file)) for (module, file), local in import_table.items()
         if local not in preserved_locals},
        key=lambda t: t[1])
    generated_import_lines = [f"import {local} from '{path}'" for local, path in generated_imports]

    pre = (pre[:first_import_idx] + preserved + generated_import_lines
           + pre[last_import_idx + 1:])

    # Helper functions: inserted once, right before the ADAPTERS map, kept
    # out of the way of the map literal itself so hand-written entries above
    # the marker never see them.
    helper_marker_idx = None
    for i, l in enumerate(pre):
        if l == HELPER_MARKER:
            helper_marker_idx = i
            break
    if helper_marker_idx is not None:
        map_open_idx_in_pre = len(pre) - 1
        pre = pre[:helper_marker_idx] + pre[map_open_idx_in_pre:]
    map_open_line = pre[-1]
    pre = pre[:-1] + [HELPER_MARKER, ''] + HELPER_BLOCK.split('\n') + ['', map_open_line]

    generated_entries = [gen_entry(e, import_table) for e in selected]

    out_lines = pre + hand_written + [MARKER] + generated_entries + ['])'] + post

    open(args.out, 'w', encoding='utf-8').write('\n'.join(out_lines))
    print(f'wrote {len(selected)} generated adapters to {args.out}')


if __name__ == '__main__':
    main()
